export { default as ForegetPage } from "./forget/ForegetPage";
export { default as Loginpage } from "./login/Loginpage";
export { default as Homepage } from "./home/Homepage";
export { default as Verification } from "./verification/Verification";
export { default as VegePage } from "./vegepage/VegePage";
export { default as CartPage } from "./cartPage/cartPage";
export { default as TablePage } from "./tablePage/TablePage";
export { default as ResetPwd } from "./reset/ResetPwd";
export { default as Signup } from "./signup/Signup";